name: Nightwatch.js Market Watch Regression Test
run-name: ${{ github.actor }} is running Market Watch Regression Test on GitHub Actions 🚀

on:
    push:
      branches:
        - main

jobs:
  regtest:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Set Up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'

    - name: Install Dependencies
      run: npm install
    
    - name: Setup ChromeDriver
      run: |
        CHROMEDRIVER_VERSION=$(npm info chromedriver version)
        CHROMEDRIVER_DIR=$RUNNER_TOOL_CACHE/chromedriver/$CHROMEDRIVER_VERSION/x64
        CHROMEDRIVER_PATH=$CHROMEDRIVER_DIR/chromedriver

        if [ ! -f "$CHROMEDRIVER_PATH" ]; then
          mkdir -p $CHROMEDRIVER_DIR
          curl -sS -L https://chromedriver.storage.googleapis.com/$CHROMEDRIVER_VERSION/chromedriver_linux64.zip -o chromedriver.zip
          unzip chromedriver.zip -d $CHROMEDRIVER_DIR
          rm chromedriver.zip
          chmod +x $CHROMEDRIVER_PATH
        fi

        echo "##[add-path]$CHROMEDRIVER_DIR"
        echo "##vso[task.prependpath]$CHROMEDRIVER_DIR"
      shell: bash

    - name: Run Regression Testing for Nightwatch.js Tests and Generate HTML Report
      run: npm run testregression

    - name: Report Front End HTML Preview
      id: html_preview_fe
      uses: pavi2410/html-preview-action@v2
      with:
        html_file: ./tests_output/be/nightwatch-html-report/index.html

    - name: Report Back End HTML Preview
      id: html_preview_be
      uses: pavi2410/html-preview-action@v2
      with:
        html_file: ./tests_output/fe/nightwatch-html-report/index.html
        
        
