name: Nightwatch.js Market Watch Regression Test
run-name: ${{ github.actor }} is running Market Watch Regression Test on GitHub Actions 🚀

on:
    push:
      branches:
        - main

jobs:
  regtest:
    runs-on: windows-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Set Up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'

    - name: Install Dependencies
      run: npm install
    
    - name: Setup ChromeDriver
      uses: nanasess/setup-chromedriver@v2
    - run:  chromedriver --url-base=/wd/hub &

    - name: Create Reports Directory
      run: |
          mkdir tests_output/fe/nightwatch-html-report
          mkdir tests_output/be/nightwatch-html-report
      
    - name: Run Regression Testing for Nightwatch.js Tests and Generate HTML Report
      run: npm run testregression

    - name: Upload Frontend Report
      uses: actions/upload-artifact@v4.3.1
      with:
        name: frontend-report
        path: tests_output/fe/nightwatch-html-report

    - name: Upload Backend Report
      uses: actions/upload-artifact@v4.3.1
      with:
        name: backend-report
        path: tests_output/be/nightwatch-html-report
